apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: wac-hospital
spec:
  interval: 1m0s  # interval v ktorom ho sleduje - robi pull repo zo zadanej url 
  ref:
    branch: main  
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/LuciaMurzova/ambulance-gitops