apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: install
  namespace: wac-hospital

spec:
  wait: true
  force: true
  dependsOn:
  - name: prepare   # pred tym ako sa zacne aplikovat tato kustomizacia, musi prejst prepare; ak je tam chyba, tato sa nepusti
  interval: 120s
  path: clusters/localhost/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo