apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
 app.kubernetes.io/part-of: wac-hospital
 app.kubernetes.io/name: xmurzova-ambulance-wl

resources:
 - ../../../apps/xmurzova-ambulance-ufe
 - ../../../apps/xmurzova-app-ambulance-ufe


components:
 - ../../../components/version-release
 - ../../../components/app-version-release