apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xmurzova-app-ambulance-ufe
spec:
  module-uri: http://xmurzova-app-ambulance-ufe.wac-hospital/build/app-ambulance-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: xmurzova-app-ambulance-app    # element, ktorý bude vložený na  stránku
                                    # pri navigácii na zoznam čakajúcich
      # attributes:
      # - name: api-base
      #   value: http://localhost:5000/api
      # - name: ambulance-id
      #   value: bobulova                                    
      path: xmurzova-app-ambulance      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: xmurzova - Zoznam ambulancií     # názov mikro aplikácie
      details: Spravuje zoznam ambulancií pre jednotlivé oddelenia
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach